app:
  redis:
    enabled: true
    conn: 127.0.0.1:6379
    dbNum: 8
    password: "123"
    timeout: 3000
    sentinel:
     enabled: false
     master: bookMaster
     nodes: "1270.0.1:6379,127.0.0.1:26379,127.0.0.1:36379"